baseURL: "https://vielfalt-ag.xyz"
theme: PaperMod
languageCode: "de-de"
title: "Vielfalt AG"
enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
  disableXML: true
  minifyOutput: true

params:
  # env: production
  keywords: [ Blog, News, School ]
  description: "Die Vielfalt AG des Gymnasium Oldenfelde"
  author: Ahmed Sami
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  mainSections:
    - posts

  fuseOpts:
    isCaseSensitive: false
    shouldSort: false
    location: 0
    distance: 500
    threshold: 0.1
    minMatchCharLength: 2
    keys: [ "title", "permalink", "summary", "content" ]

  assets:
    disableFingerprinting: false
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/apple-touch-icon.png"

outputs:
  home:
    - HTML
    - JSON

defaultContentLanguageInSubdir: false
defaultContentLanguage: de

languages:
  de:
    contentDir: content/de
    languageName: "German"
    weight: 1
    DateFormat: "2 January, 2006"
    title: Vielfalt AG
    menu:
      main:
        - name: Kategorien
          url: categories
          weight: 1
        - name: Tags
          url: tags
          weight: 2
        - name: Suchen
          url: search
          weight: 3
        - name: Archiv
          url: archives
          weight: 4
        - name: Ãœber uns
          url: posts/about
          weight: 5
    homeInfoParams:
      Title: "Vielfalt AG ğŸŒˆ"
      Content: >
        Platzhalter text blah blah
        - Weitere Infos finden Sie **[hier](about/)**.

  en:
    contentDir: content/en
    languageName: "English"
    weight: 2
    DateFormat: "January 2, 2006"
    title: Vielfalt AG
    menu:
      main:
        - name: Categories
          url: categories
          weight: 1
        - name: Tags
          url: tags
          weight: 2
        - name: Search
          url: search
          weight: 3
        - name: Archive
          url: archives
          weight: 4
        - name: About us
          url: posts/about
          weight: 5
    homeInfoParams:
      Title: "Vielfalt AG ğŸŒˆ"
      Content: >
        Platzhalter text blah blah
        - You can find out more **[here](about/)**.


markup:
  goldmark:
    renderer:
      unsafe: true
