baseURL: "https://add1609.github.io/vielfalt/"
theme: PaperMod
languageCode: "en-us"
title: "Vielfalt AG"
enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
  disableXML: true
  minifyOutput: true

params:
  # env: production
  keywords: [ Blog, News, School ]
  author: Ahmed Sami
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

defaultContentLang: en

languages:
  en:
    contentDir: content/en
    languageName: "English"
    DateFormat: "January 2, 2006"
    title: Vielfalt AG
    menu:
      main:
        - name: a
          url: nil
          weight: 1
        - name: b
          url: nil
          weight: 2
        - name: Search
          url: search
          weight: 3
        - name: Archive
          url: archives
          weight: 4
        - name: About us
          url: about
          weight: 5

  de:
    contentDir: content/de
    languageName: "German"
    DateFormat: "2 January, 2006"
    title: Vielfalt AG
    menu:
      main:
        - name: a
          url: nil
          weight: 1
        - name: b
          url: nil
          weight: 2
        - name: Suchen
          url: search
          weight: 3
        - name: Archiv
          url: archives
          weight: 4
        - name: Ãœber uns
          url: about
          weight: 5


markup:
  goldmark:
    renderer:
      unsafe: true
